### ISSUE TITLE
Redstone Dust not allowing removal from Crate - Standard

### ISSUE THREAD

**Issue by poppyseed0054** [grondag/facility#8]
Hi there, Love your mod so far. The search function is the best, thank you so much!! 

Only found one issue where I can't remove Redstone Dust from the **Crate - Standard**. Redstone Block is fine though, and I think I have tested all the other items with no issues.

*EDIT* Same issue with **Stone**.
I disabled Roughly Enough Items and this fixed this issue with Redstone Dust and Stone, but now I have the same issue with Chiseled Stone Bricks (lol).

I have seven **Crate - Standard** joined together (11, 655 items).

I am running the following mods on 1.16 snapshot (20w06a)
Adorn-1.8.0+20w06a
Autofish-0.8.5-fabric-mc1.15
chunk-activator-1.2.0+mc1.14.4
coloredcampfire-1.1.3
Couplings-1.3.1
diggusmaximus-1.2.6
exotic-blocks-mc116-1.2.113
exotic-matter-mc116-1.18.302
extradoors-1.5.0-1.16
fabric-api-0.4.33+build.299-1.16
fabric-language-kotlin-1.3.61+build.1
facility-mc116-0.7.123
floradoubling-1.15.2-20w06a-1.0.0
Hwyla-fabric-1.15-pre4-1.9.19-70
InstantLava_Fabric1.15-1.1.3
InventorySorter-1.6.3.disabled
LightOverlay-4.2
linkedstorage-1.2.0
mamiyaotaru
nomadbooks-0.3
PaintZ+1.2
RoughlyEnoughItems-4.0.4-unstable.202002211427
terrestria-1.3.1+build.3
trapexpansion-1.3.1-fabric1.15
yet-another-gravestone-mod-1.2.1

Cheers,

Julie

**Comment by rpmm24** [comment]
same issue but but its my diamonds and iron blocks ;(

**Comment by grondag** [comment]
Not able to reproduce this yet.  Could I get a copy of logs?  A world save file could also be useful.

Also, what happens when you try to remove the items?  Does it just ignore your click or does something else happen?   

If you break the crates access them from inventory or place them down again does that clear the problem?

My guess is that it doesn't matter what other mods are installed and the block itself also doesn't matter.  Instead there's probably some sequence of events that gets the system into a state where it is confused.

So, any info you can provide to help reproduce will make it easier for me to find/fix it.

Thanks for checking out my mod and for reporting bugs!

**Comment by grondag** [comment]
Unable to reproduce this problem in current builds.  If this is still happening, please reopen.
